// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGZECWARBY_7qL2JaYtLUYqs-bJTEqjJc',
    appId: '1:1016480461147:web:e4b70041cc4fa14d1f2a7e',
    messagingSenderId: '1016480461147',
    projectId: 'classmate-78f10',
    authDomain: 'classmate-78f10.firebaseapp.com',
    storageBucket: 'classmate-78f10.appspot.com',
    measurementId: 'G-6RT9M83E6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCod35j9tI-XVlnCkOyU0XmmDjRhrEj5NI',
    appId: '1:1016480461147:android:af36f88bd8cf41e31f2a7e',
    messagingSenderId: '1016480461147',
    projectId: 'classmate-78f10',
    storageBucket: 'classmate-78f10.appspot.com',
  );
}
